<script>
	import { fade } from 'svelte/transition';
	import logo from '$lib/assets/img/logo.svg';
	export let loaderColor = 'var(--green-dark-color)';
</script>

<div class="loading d-flex justify-cc align-center" style="background-color:{loaderColor}">
	<svg
		xmlns="http://www.w3.org/2000/svg"
		xmlns:xlink="http://www.w3.org/1999/xlink"
		style="margin: auto; display: block; shape-rendering: auto;"
		width="150px"
		height="150px"
		viewBox="0 0 100 100"
		preserveAspectRatio="xMidYMid"
	>
		<path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#d6e15b" stroke="none">
			<animateTransform
				attributeName="transform"
				type="rotate"
				dur="1s"
				repeatCount="indefinite"
				keyTimes="0;1"
				values="0 50 51;360 50 51"
			/>
		</path>
		<!-- [ldio] generated by https://loading.io/ --></svg
	>
</div>

<style>
	.loading {
		position: fixed;
		left: 0;
		top: 0;
		width: 100%;
		height: 100%;
		z-index: 2;
		background-color: var(--green-dark-color);
		color: var(--white);
	}
	.logo_bg {
		width: 180px;
	}
</style>
